# Generated by Django 5.1.3 on 2025-05-25 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TModeler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField(blank=True, default=-1, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('sex', models.IntegerField(blank=True, default=0, null=True)),
                ('state', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TModeler.state')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
